version: "3"
services:

  php-apache:
    image: webdevops/php-apache:8.1-alpine
    container_name: php-server
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./php:/usr/local/etc/php
    networks:
      - mynetwork

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    ports:
      - '3306:3306'
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-server"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge